ltp: Autospec creation for update from version 20220527 to version 20220930
Amir Goldstein (22):
      syscalls/inotify12: Introduce test for inotify mask flags
      syscalls/fanotify23: Introduce FAN_MARK_EVICTABLE test
      syscalls/fanotify10: Watch directory that is not the mount path
      syscalls/fanotify10: Fix ignored mark path in test case 17
      syscalls/fanotify10: Mount cycle between test cases
      syscalls/fanotify10: Add test cases for evictable ignore mark
      syscalls/fanotify09: Cleanup open event fds on error
      syscalls/fanotify09: Verify if no events are expected
      syscalls/fanotify09: Tidy up the test to make it more readable
      syscalls/fanotify09: Add test cases for merge of ignore mask
      syscalls/fanotify14: Encode the expected errno in test case
      syscalls/fanotify14: Add test cases for events not allowed on non-dir
      syscalls/fanotify09: Add test cases for FAN_MARK_IGNORE
      syscalls/fanotify14: Require FAN_REPORT_FID support for entire test
      syscalls/fanotify14: Add test cases for FAN_MARK_IGNORE
      syscalls/fanotify10: Avoid undesired event in test
      syscalls/fanotify10: Add more verifications and debug info
      syscalls/fanotify10: Use dedicated mark type for inode mark on parent
      syscalls/fanotify10: Run tests with two ignore mask variants
      syscalls/fanotify10: Test FAN_MARK_IGNORE with FAN_EVENT_ON_CHILD
      syscalls/fanotify10: Test FAN_MARK_IGNORE with FAN_ONDIR
      syscalls/fanotify09: Make test case definitions more readable

Andrea Cervesato (12):
      Rewrite mesgq_nstest.c using new LTP API
      Rewrite msg_comm.c using new LTP API
      Rewrite sem_comm.c using new LTP API
      Rewrite sem_nstest.c using new LTP API
      Rewrite semtest_2ns.c using new LTP API
      Rewrite shmnstest.c using new LTP API
      Rewrite shmem_2nstest.c using new LTP API
      Rewrite shm_comm.c using new LTP API
      Remove libclone dependency from sysvipc test suite
      Delete ipcns_helper.h in the sysvipc test suite
      Fix description for pidns01 and pidns02 tests
      Remove obsolete LTPROOT usage in math runtest file

Andrea Cervesato via ltp (6):
      Refactor pidns01 test using new LTP API
      Refactor pidns02 test using new LTP API
      Refactor pidns03 test using new LTP API
      Refactor pidns20 test using new LTP API
      Refactor pidns32 test using new LTP API
      Improve safe_setxattr error message on ENOTSUP

Avinesh Kumar (50):
      Rewrite utime01.c using new LTP API
      Rewrite utime02.c using new LTP API
      utime03.c: Remove unnecessary header includes
      Rewrite utime04.c using new LTP API
      Rewrite utime05.c using new LTP API
      Rewrite utime06.c using new LTP API
      Docparse correction in C test tutorial
      open02.c: convert comment to docparse
      open02.c: remove redundant headers and a typo fix
      open08.c: Docparse format and rewording of description
      open08.c: Remove redundant headers
      Typo and grammar corrections in the documentation
      open08.c: Use TST_EXP_FAIL2(), SAFE_CLOSE()
      Rewrite rename01.c using new LTP API
      Remove rename02.c
      Rewrite rename03.c using new LTP API
      Rewrite rename04.c using new LTP API
      Rewrite rename05.c using new LTP API
      Rewrite rename06.c using new LTP API
      Rewrite rename07.c using new LTP API
      Rewrite rename08.c using new LTP API
      Rewrite rename10.c using new LTP API
      nice0[1-4]: Turn comment into docparse
      readahead01.c: use TST_EXP_FAIL() macro and fix warnings
      readahead01.c: turn comment into docparse and reword
      rename12.c: Convert to new LTP API
      rename13.c: Convert to new LTP API
      API/fs: Typo fixes in comments
      dup204.c: use TST_EXP_VAL() and TST_EXP_EQ_LU() macros
      fstat02.c: simplify using TST_EXP_*() macros
      setuid01: use TST_EXP_PASS() macro, docparse comment and reword
      Remove open05.c
      alarm02: simplify using TST_EXP_* macros
      alarm03: cleanup and simplify
      alarm05: use TST_EXP_* macros
      alarm06: cleanup and simplify
      alarm07: cleanup and simplify
      open06.c: convert to new LTP API
      setegid01.c: Rewrite using new LTP API
      inotify_init1_01.c: Convert to new LTP API
      inotify_init1_02.c: Convert to new LTP API
      getpagesize01: Rewrite using new LTP API
      write04.c: use TST_EXP_FAIL() macro
      syscalls/truncate03.c: use TST_EXP_FAIL() macro
      open04.c: convert to new LTP API
      getsid01.c: Convert to new LTP API
      getsid02.c: Rewrite using new LTP API
      unlink07: use TST_EXP_FAIL(), docparse format
      unlink08: use TST_EXP_FAIL(), turn comment into docparse and reword, copyright update
      statx04: skip test on ntfs filesystem

Bogdan Lezhepekov (1):
      mc_opts/mc_verify_opts.c: Initialize local variable

Chen Hanxiao (2):
      syscalls/mount_setattr01: Add basic functional test
      docparse/Makefile: fix a typo

Cristian Marussi (1):
      Fix mountns01/02/03/04 final umounts using more peculiar dir names

Cyril Hrubis (12):
      syscalls/perf_event_open03: Fix include
      syscalls/futex_cmp_requeue01: Remove unused tst_timer_test.h
      syscalls/execve06: Add test for argv[0] = NULL
      syscalls/fork13: Rewrite to new API + add .max_runtime
      openposix: pthread_rwlockattr_getpshared/2-1: Fix
      openposix: pthread_spin_init/{2-1,2-2}: Fix
      openposix: sem_destroy/3-1: Fix
      openposix: sem_timedwait/11-1: Fix
      openposix: aio_h/2-1: Add return at the end of main()
      openposix: mq_timedreceive: Silence warning
      opeposix: pthread_barrierattr_getpshared/2-1: Simplify codeflow
      lapi/io_uring.h: Add missing semicolon

Dylan Jhong (3):
      fs_bind: Fix incorrect mount option
      semctl03: Prevent segfault in glibc when __IPC_TIME64 is defined
      kernel/uevent: Adjust the number of uevents dynamically in uevent02

Edward Liaw (6):
      syscalls/pread02_64: format string for 64-bit offset
      syscalls/timerfd04: incorrect CLOCK_BOOTIME end
      syscalls/signal06: loop being clobbered by syscall on clang
      lapi/name_to_handle.h: fix include
      Revert "m4: Remove check for io_set_eventfd"
      minmax: fix type warnings

Hongchen Zhang (2):
      syslog11: convert to new LTP API
      syslog11: save and restore console log level

Huangjie Liao (1):
      syscalls/openat01: Convert into new api

Jan Kara (1):
      syscalls/fanotify10: Make evictable marks test more reliable

Jan Stancek (7):
      syscalls/utime03: print more details when test fails
      syscalls/migrate_pages03: restore runtime to 5m
      commands/df01.sh: print more logs when test fails
      syscalls/futex_waitv03: replace TST_THREAD_STATE_WAIT with repeated wake
      syscalls/accept4_01: don't hardcode port number for test
      syscalls/delete_module: drop static declaration
      syscalls/fsync02: restore runtime to 5m

Joerg Vehlow (5):
      net_stress: Fix usage of variables from tst_net.sh
      memcg/functional: Fix usage of PAGESIZE from memcg_lib.sh
      openposix: Fix existence test for local flag-files
      openposix: Setup autoconf and fix installation layout
      configure: Integrate open posix testsuite configure

Jun Huang (1):
      pm_include.sh: Fix calculation error of no_of_sockets

Khem Raj (1):
      rt-migrate: Use int instead of pthread_t for thread IDs

Leo Yu-Chi Liang (1):
      syscalls/times03.c: Fix typos

Li Wang (10):
      lib: extend .request_hugepages to guarantee enough hpages
      memfd_create03: make use of new .hugepages
      pkey01: print more info when write buff fail
      madvise06: shrink to 3 MADV_WILLNEED pages to stabilize the test
      swapping01: make use of remaining runtime in test looping
      mountns0[1-3]: wait for umount completed in thread_b
      lapi/pidfd: adding pidfd header file
      lapi/fsmount: resolve conflict in different header files
      statx04: mask STATX_ATTR_COMPRESSED on tmpfs
      open04: add EMFILE check

Luke Nowakowski-Krijger (19):
      API/cgroup: Modify tst_cg_print_config for parsing and consumption
      API/cgroup: Add option for specific pid to tst_cg_opts
      API/cgroup: Add cgroup_find_root helper function
      API/cgroup: Add CTRL_NAME_MAX define
      tst_test_macros: Add TST_TO_STR and TST_STR macro
      API/cgroup: Implement tst_cg_load_config
      API/cgroup: Add more controllers to tst_cgroup
      API/cgroup: refuse to mount blkio when io controller is mounted
      testcases/lib: Implement tst_cgctl binary
      controllers: Expand cgroup_lib shell library
      controllers: Update cgroup_fj_* to use newer cgroup lib and test lib
      controllers: Update memcg_control_test to newer test lib and cgroup lib
      controllers: Update memcg/regression/* to new test and cgroup lib
      controllers: Update memcg_stress_test to use newer cgroup lib
      controllers: update memcg/functional to use newer cgroup lib
      controllers: Update pids.sh to use newer cgroup lib
      controllers: update cpuset_regression_test.sh to use newer cgroup lib
      controllers: update cgroup_regression_test to use newer cgroup lib
      API/cgroup: Add rdma controller

Luo xiaoyu (1):
      syscalls/open03.c: Rewrite open03.c using new LTP API

Martin Doucha (26):
      kvm: Fix stack access mode in KVM test ELF headers
      configure: Check for KVM linker script support
      Add KVM_LD Makefile variable for building KVM payload binaries
      tst_rod: Use args[0] as the command name
      snd_timer01: Add missing tst_fzsync_start_race_*() calls
      syscalls/pty06: Add CVE reference
      cve-2017-2671: Increase max_runtime
      csf_bandwidth01: Add max_runtime
      du01.sh: Fix broken directory change
      du01.sh: Avoid l10n issues
      tst_rod: Fail on directory change commands
      inotify11: Fix race condition between fork() and inotify init
      copy_file_range01: Add max_runtime
      Add tst_validate_children() helper function
      Make io_read() runtime-aware
      dio_sparse: Fix child exit code
      ioctl_sg01: Add max_runtime
      perf_event_open02: Add max_runtime
      readahead02: Add max_runtime
      sendfile09: Add max_runtime
      ksm: Add max_runtime to tests
      request_key03: Refactor child process code
      request_key03: Split test into 3 testcases
      request_key03: Add max_runtime and make children runtime-aware
      tst_fs_type_name(): Add VFAT support
      tst_supported_fs: Implement checking paths against skiplist

Petr Vorel (98):
      ci: Ubuntu xenial -> bionic
      doc: Update supported versions
      tst_net.sh: Fix for disabled IPv6
      netns: Rewrite to use tst_net.sh
      netns: Rename netns_helper.sh -> netns_lib.sh
      rpc: Remove rup01.sh test
      rpc: Remove rusers01.sh test
      rpc: Move rest of RPC tests to runtest/net.rpc_tests
      Fix more typos s/atleast/at least/
      pty03: Convert doc into docparse
      Fix typo s/possitive/positive/
      tst_test.sh: Allow -i0
      tst_test: Check for -i >= 0
      doc/maintainer: Check also -i0
      tst_kvercmp.sh: Use /bin/sh shebang
      mc_opts: Fix warnings, add copyright and SPDX
      kvm: Fix compilation on x86
      kvm: Fix undefined reference to __stack_chk_fail()
      docparse: Use -- as ndash
      nfs05_make_tree: Restore 5 min timeout
      doc/c-test-api: Turn comment into docparse
      ci/ubuntu: impish -> jammy
      utime: Remove useless tag needs_tmpdir
      tst_device: Remove unnecessary braces
      tst_test.sh: Add $TST_MOUNT_DEVICE
      df01.sh: Use TST_MOUNT_DEVICE=1
      tst_test.sh: allow ' in pattern for allowed variables
      shell: Add test for TST_MOUNT_DEVICE=1
      README: Mention ML archive on lore
      netstress: Restore runtime to 5m
      Fix spelling error: exitting
      pty04: Use TST_TO_STR_ macro
      route-change-netlink: Use TST_TO_STR macro
      tst_cgroup: Remove unused variable
      tst_cgroup: Fix -Wstringop-truncation warning
      tst_cgroup: Add macro
      tst_kernel: Fix search for foo-x86-64 module
      tst_check_driver.sh: Add test for x68_64 module
      tst_format_device.sh: Remove -O quota from TST_DEV_FS_OPTS
      tst_test.sh: Fix $@ usage on older dash releases
      Fix typos in comments
      tst_fs.h: Fix formatting
      tst_test.sh: runtest.sh: Remove unused code
      tst_ansi_color.sh: Allow to run with set -e
      tst_test.sh: Fix _tst_cleanup_timer() on set -e
      generate_lvm_runfile.sh: Fix bashism
      ftrace_lib.sh: Remove array
      ftrace_lib.sh: Minor formatting cleanup
      github: pull_request_template.md
      doc/c-test-tutorial-simple.txt: Use links, README.md
      df01.sh: Use $TST_MNTPOINT
      df01.sh: Simplify style
      mkfs01.sh: Simplify style
      mkfs01.sh: Use $TST_MNTPOINT, remove useless mkdir
      Fix typo s/exitted/exited/
      doc: Inline .save_restore, add more examples
      tst_fs.h: tst_fs_type.c: Update copyright, use SPDX
      Fix typo s/filesytem/filesystem/
      write04: Convert to docparse, update copyright
      tst_test.sh: Fix tst_mkfs() for tmpfs
      tst_device: Add clear command
      tst_test.sh: Allow $ ; after whitelisted variable
      tst_mount_device.sh: Cover early tst_umount call
      tst_test: Add === marks to "Testing filesystem" message
      execlp01.c: Fix formatting to make checkpatch happy
      ci/alpine: Enable getcontext01.c
      unlink07: unshare02: Add man section numbers
      include: Move stringification macros to tst_common.h
      doc: Document macros for stringification
      fanotify.h: Keep checkpatch.pl happy
      tst_test_macros: Add TST_EXP_FD_OR_FAIL() macro
      fanotify20: Simplify code
      fanotify14: Use TST_EXP_FD_OR_FAIL()
      shell: Print mount command in tst_mount()
      shell API/tests: Require root for format/mount tests
      Add .mailmap
      tst_test.sh: Print Summary into stderr
      tst_supported_fs: Implement skip list
      zram01.sh: Use tst_supported_fs -s tmpfs
      tst_supported_fs: Support skip list when query single fs
      shell: Add $TST_SKIP_FILESYSTEMS + tests
      tst_test.sh: Add $TST_ALL_FILESYSTEMS
      tst_test.sh: Allow | after whitelisted variable
      shell: Add tests for TST_ALL_FILESYSTEMS=1
      df01.sh: Convert to TST_ALL_FILESYSTEMS=1
      tst_device: Increase DEV_SIZE_MB to 300 MB
      lib/tests: Increase .dev_min_size
      doc/user-guide: LTP_RUNTIME_MUL is only for C API
      tst_test.sh: Remove unused variable
      tst_supported_fs: Unify messaging
      tst_supported_fs: Fix return codes
      tst_test.sh: Fix filesystem support detection
      tst_test.sh: cd to $LTPROOT before umount
      ima_setup.sh: Use TST_MOUNT_DEVICE
      ima_setup.sh: Use tst_supported_fs instead of df
      zram01.sh: Fix minimal size for XFS on kernel 5.19
      tst_test.sh: Fix missing cleanup run from setup
      LTP 20220930

Richard Palethorpe (9):
      Create policy for testing unstable kernel features
      API/bpf: Copy more map and function types from kernel
      syscalls/bpf: Add test for CVE-2021-4204
      syscalls/bpf: Add test for CVE-2022-23222
      tools: Check headers with checkpatch.pl
      read_all: Add worker timeout and rewrite scheduling
      read_all: Fix type warnings
      read_all: Allow /sys/power/wakeup_count
      read_all: Prevent FNM_EXTMATCH redefinition

Rong Tao (2):
      tlibio: Increase Errormsg size
      fanotify21: fix compile complain

Ross Burton (1):
      kvm: use $(LD) instead of hardcoding ld

Sharan Turlapati (1):
      run-posix-option-group-test.sh: Warn when run without compilation

Tudor Cretu (5):
      lib: Fix initialization of recursive mutex
      syscalls/mprotect01: Invoke the syscall directly instead of the libc wrapper
      syscalls/prctl04: Allow rt_sigprocmask in the syscall filter
      syscalls/statfs02, fstatfs02: Convert to new API
      syscalls/statfs02, fstatfs02: Accept segfault instead of EFAULT

Xiao Liang (1):
      zram03: unload zram when it is loaded during test run

Xiao Yang (1):
      syscalls: Use anonymous .resource_files for docparse

Yang Xu (12):
      syscalls/shmdt01: Convert into new api
      syscalls/shmdt02: Convert into new api
      syscalls/fcntl05: Convert into new api
      mountns04: Use needs_tmpdir instead of needs_checkpoints
      tst_cgroup: Fix typo
      security/dirtypipe: Add test for CVE-2022-0847
      syscalls/prctl: Add docparse formatting
      syscalls/prctl: make check happy
      tst_safe_file_at: Add SAFE_FCHOWNAT macro
      tst_cgroup: Add safe_cg_open and safe_cg_fchown functions
      cgroup_core01: copy from kernel selftest test_cgcore_lesser_euid_open
      syscalls/creat09: Add umask test condition

Zhao Gongyi (5):
      test_children_cleanup: Add test_children_cleanup to .gitignore
      tst_kvercmp.sh: strip '+' when $(EXTRAVERSION) is blank
      cpuhotplug*.sh: Check return value of online_cpu/offline_cpu
      lapi/io_uring.h: Fix io_uring_setup_supported_by_kernel()
      syscalls/nice: Adjust the expected priority after calling nice()

Zhao Gongyi via ltp (1):
      futex_waitv01: Add test verifies EAGIN/ETIMEDOUT